baseURL = 'https://pierretsia.github.io/cursor-tech-blog/'
languageCode = 'en-us'
title = 'Modern Tech Insights'
theme = 'PaperMod'

# Enable SEO features
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
  env = "production"
  description = "A modern tech blog exploring the latest in software development and technology"
  keywords = ["Tech", "Software Development", "Programming", "Web Development", "Technology"]
  author = "Tech Enthusiast"
  images = ["/images/logo.svg"]
  DateFormat = "January 2, 2006"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

[params.profileMode]
  enabled = false
  title = "Modern Tech Insights"
  subtitle = "Exploring the cutting edge of technology"
  imageUrl = "/images/logo.svg"
  imageTitle = "Modern Tech Insights Logo"

[params.homeInfoParams]
  Title = "Welcome to Modern Tech Insights"
  Content = "Exploring the cutting edge of technology through in-depth articles and analysis"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/PierreTsia"

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/yourusername"

[params.analytics.google]
  SiteVerificationTag = "XYZ"

[params.assets]
  favicon = "/images/logo.svg"
  favicon16x16 = "/images/logo.svg"
  favicon32x32 = "/images/logo.svg"
  apple_touch_icon = "/images/logo.svg"
  safari_pinned_tab = "/images/logo.svg"

[params.cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = false

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]
