baseURL = 'https://pierretsia.github.io/cursor-tech-blog/'
languageCode = 'en-us'
title = 'Modern Tech Insights'
theme = 'PaperMod'

# Enable SEO features
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
  env = "production"
  description = "A modern tech blog exploring the latest in software development and technology"
  keywords = ["Tech", "Software Development", "Programming", "Web Development", "Technology"]
  author = "Tech Enthusiast"
  images = ["images/logo-dark.svg"]
  DateFormat = "January 2, 2006"
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = true

[params.profileMode]
  enabled = false
  title = "Modern Tech Insights"
  subtitle = "Exploring the cutting edge of technology"
  imageUrl = "/images/logo.svg"
  imageTitle = "Modern Tech Insights Logo"

[params.homeInfoParams]
  Title = "Welcome to Modern Tech Insights"
  Content = """
Exploring the cutting edge of technology through in-depth articles and analysis.
Focused on AI, software development, and the future of tech."""

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/PierreTsia"

[params.analytics.google]
  SiteVerificationTag = "XYZ"

[params.assets]
  disableHLJS = true
  favicon = "images/logo-dark.svg"
  favicon16x16 = "images/logo-dark.svg"
  favicon32x32 = "images/logo-dark.svg"
  apple_touch_icon = "images/logo-dark.svg"
  safari_pinned_tab = "images/logo-dark.svg"

[params.cover]
  linkFullImages = true
  responsiveImages = true

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]
